name: Random Rantings
favicon: null
layout_spectrum: 0.50433
typography_spectrum: 0.10663
title: Random Rantings of Jordan Drew
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#9b9187'
    - '#bfb4a2'
    - '#3b3734'
    - '#ffefd1'
  brandStrength: 0.25
  lightness: 0
  saturation: 0.8125
  rhythmicContrast: 0
purpose: []
