name: Random Rantings
favicon: null
layout_spectrum: 0.47584
typography_spectrum: 0.05239
title: Random Rantings of Jordan Drew
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#412959'
    - '#815684'
    - '#b47798'
    - '#d595a5'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
