name: Random Rantings
favicon: null
layout_spectrum: 0.16983
typography_spectrum: 0.12289
title: Random Rantings of Jordan Drew
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#d8d3da'
    - '#487f00'
    - '#af819e'
  brandStrength: 0.1875
  lightness: 0
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
