name: Random Rantings
favicon: null
layout_spectrum: 0.16983
typography_spectrum: 0.11205
title: Random Rantings of Jordan Drew
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#b59ab9'
    - '#9e697b'
    - '#76204f'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
