name: Random Rantings
favicon: null
layout_spectrum: 0.28252
typography_spectrum: 0.05239
title: Random Rantings of Jordan Drew
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#8e7e6e'
    - '#fefefe'
    - '#382b1a'
    - '#b4a796'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
