name: Random Rantings
favicon: null
layout_spectrum: 0.28252
typography_spectrum: 0.05239
title: Random Rantings of Jordan Drew
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e1cd6c'
    - '#3e4e57'
    - '#e86f53'
    - '#000000'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
