name: Random Rantings
favicon: null
layout_spectrum: 0.50433
typography_spectrum: 0.10663
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#654900'
    - '#dbbe00'
    - '#c5e7cf'
    - '#79996a'
  brandStrength: 0.8125
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
