name: Random Rantings
favicon: null
layout_spectrum: 0
typography_spectrum: 0.12289
title: Random Rantings of Jordan Drew
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#a3c686'
    - '#3f4a36'
    - '#546942'
    - '#111e0a'
  brandStrength: 0.75
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
