name: Random Rantings
favicon: null
layout_spectrum: 0.37424676422961056
typography_spectrum: 0.630560769001022
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.22123153298161924
  lightness: 0.5640305122360587
  saturation: 0.5065763622988015
  rhythmicContrast: 0.5515178549103439
purpose: []
