name: Random Rantings
favicon: null
layout_spectrum: 0.66874
typography_spectrum: 0.630560769001022
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#85857d'
    - '#f9db93'
    - '#0e1e38'
    - '#c2af77'
    - '#44673d'
  brandStrength: 0.22123153298161924
  lightness: 0.5640305122360587
  saturation: 0.5065763622988015
  rhythmicContrast: 0.5515178549103439
purpose: []
